"""add_user_table

Revision ID: 39728b1291ba
Revises: 
Create Date: 2023-03-08 13:38:04.738079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39728b1291ba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
